version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4

    steps:
      - checkout
      - run: go version
      - run: go run oya.go run develop
      - run: go run oya.go run test
